#!/bin/sh
# vim: set ts=4:
set -eu

. "$(dirname "$0")"/utils.sh

if [ -z "${encrypted_78618cd8dc6b_key:-}" ]; then
	ewarn 'Decryption key is not available'
	exit 0
fi

einfo 'Decrypting .deploykey'
openssl aes-256-cbc \
	-K "$encrypted_78618cd8dc6b_key" \
	-iv "$encrypted_78618cd8dc6b_iv" \
	-in .deploykey.enc -out .deploykey -d
chmod 600 .deploykey
